export enum ClientEvents {
  MESSAGE_SEND = 'message:send',
  MESSAGE_EDIT = 'message:edit',
  MESSAGE_DELETE = 'message:delete',
  MESSAGE_REACT = 'message:react',
  MESSAGE_READ = 'message:read',
  TYPING_START = 'typing:start',
  TYPING_STOP = 'typing:stop',
  PRESENCE_PING = 'presence:ping',
  CONVERSATION_JOIN = 'conversation:join',
  CONVERSATION_LEAVE = 'conversation:leave',
  CALL_INITIATE = 'call:initiate',
  CALL_ACCEPT = 'call:accept',
  CALL_REJECT = 'call:reject',
  CALL_END = 'call:end',
  CALL_SIGNAL = 'call:signal',
}

export enum ServerEvents {
  MESSAGE_NEW = 'message:new',
  MESSAGE_EDITED = 'message:edited',
  MESSAGE_DELETED = 'message:deleted',
  MESSAGE_REACTION = 'message:reaction',
  MESSAGE_SEEN = 'message:seen',
  MESSAGE_DELIVERED = 'message:delivered',
  TYPING_ACTIVE = 'typing:active',
  TYPING_STOPPED = 'typing:stopped',
  PRESENCE_UPDATE = 'presence:update',
  NOTIFICATION_NEW = 'notification:new',
  CONVERSATION_UPDATED = 'conversation:updated',
  CALL_INCOMING = 'call:incoming',
  CALL_ACCEPTED = 'call:accepted',
  CALL_REJECTED = 'call:rejected',
  CALL_ENDED = 'call:ended',
  CALL_SIGNAL_RECEIVED = 'call:signal_received',
  ERROR = 'error',
}
